In [1]:
print("hello world`")

hello world`


# tuple

In [2]:
ls = [1,2,3,4,5,6,7,8,9]
print(ls)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
import numpy 

array = numpy.array([1,2,3,4,5])

print(array)
print(numpy.__version__)


[1 2 3 4 5]
2.1.0


In [7]:
print(numpy.__version__)

2.1.0


In [8]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)



[1 2 3 4 5]


In [11]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array, array.ndim)

[1 2 3 4 5] 1


In [23]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array, array.ndim, array.size, array.shape , array.dtype)

[1 2 3 4 5] 1 5 (5,) int64


In [25]:
import numpy as np

array = np.array([7])
print(array, array.ndim)

[7] 1


In [26]:
import numpy as np

array = np.array([ [1,2],[3,4] ])
print(array, array.ndim)


[[1 2]
 [3 4]] 2


In [28]:
import numpy as np

array = np.array([ [[1,2],[3,4]],[[5,6],[7,8]] ])
print(array, array.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


In [33]:
import numpy as np

array = np.array([1,"hello",3,4])
print(array, array.ndim)
print(array[1])

['1' 'hello' '3' '4'] 1
hello


In [42]:
import numpy as np
array = np.array([ [1,2,3],[4,5,6] ])
print(array, array.ndim)
print(array[0,1])

[[1 2 3]
 [4 5 6]] 2
2


In [47]:
import numpy as np
array = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ])
print(array, array.ndim)
print(array[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 3
12


In [1]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array, array.ndim, array.size, array.shape , array.dtype)

[1 2 3 4 5] 1 5 (5,) int64


In [5]:
import numpy as np

array = [1,2,3]
array2 = [4,5,6]

arrconc = np.concatenate([array, array2])


In [6]:
arrconc

array([1, 2, 3, 4, 5, 6])

In [10]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])

print(array, array.ndim)

[[1 2 3 4]
 [5 6 7 8]] 2


In [12]:
# import numpy as np

# arr1 = [1,2,3,4,5]
# arr2 = np.array([9,8,7])
# print(arr1, arr2)

[1, 2, 3, 4, 5] [9 8 7]


In [16]:
# import numpy as np

# arr1 = np.array([[1,2],[3,4]])
# arr2 = np.array([[5,6],[7,8]])

# arrconc = np.concatenate((arr1, arr2), axis=1)

In [14]:
arrconc

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])

arrconc = np.stack((arr1, arr2), axis=1)

print(arrconc)


[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


In [24]:
# import numpy as np

# arr1 = np.array([[1,2],[4,5]])
# arr2 = np.array([[6,7],[9,0]])

# arrconc = np.stack((arr1, arr2), axis= 2)

# print(arrconc)

[[[1 6]
  [2 7]]

 [[4 9]
  [5 0]]]


In [26]:
# import numpy as np

# arr1 = np.array([[1,2],[3,4]])
# arr2 = np.array([[5,6],[7,8]])

# arrconc = np.hstack((arr1, arr2))
# print(arrconc)

[[1 2 5 6]
 [3 4 7 8]]


In [42]:
import numpy as np

array1 = np.array([1,12,3,4,5,6,17,8,9])
spl = np.array_split(array1,2)

print(spl)

[array([ 1, 12,  3,  4,  5]), array([ 6, 17,  8,  9])]


In [47]:
map?

Init signature: map(self, /, *args, **kwargs)
Docstring:     
map(func, *iterables) --> map object

Make an iterator that computes the function using arguments from
each of the iterables.  Stops when the shortest iterable is exhausted.
Type:           type
Subclasses:     

In [48]:
list?

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _List, _HashedSeq, StackSummary, _Threads, ConvertingList, DeferredConfigList, _ymd, _Accumulator, SList, _ImmutableLineList, ...

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])

# Pandas

In [1]:
import pandas as pd
data={
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [29, 34, 27, 25],
    'City': ['New York', 'London', 'Paris', 'Berlin']
}

df = pd.DataFrame(data)

In [2]:
df

Name  Age      City
0   John   29  New York
1   Anna   34    London
2  Peter   27     Paris
3  Linda   25    Berlin

In [3]:
import pandas as pd
data={
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [29, 34, 27, 25],
    'City': ['New York', 'London', 'Paris', 'Berlin']
}

df = pd.Series(data)

In [4]:
df

Name           [John, Anna, Peter, Linda]
Age                      [29, 34, 27, 25]
City    [New York, London, Paris, Berlin]
dtype: object

In [15]:
import pandas as pd

df = pd.read_csv("./csv/data2.csv")

In [16]:
df

id FirstName   Age
0  1001     Frodo    50
1  1002   Samwise    39
2  1006   Legolas  2931
3  1007    Elrond  6520
4  1008  Barromir    51

In [17]:
import pandas as pd

df = pd.read_json("./json/data.json")

In [18]:
df

userId   id                                              title  completed
0         1    1                                 delectus aut autem      False
1         1    2                 quis ut nam facilis et officia qui      False
2         1    3                                fugiat veniam minus      False
3         1    4                                   et porro tempora       True
4         1    5  laboriosam mollitia et enim quasi adipisci qui...      False
..      ...  ...                                                ...        ...
195      10  196                consequuntur aut ut fugit similique       True
196      10  197                  dignissimos quo nobis earum saepe       True
197      10  198                       quis eius est sint explicabo       True
198      10  199                       numquam repellendus a magnam       True
199      10  200                       ipsam aperiam voluptates qui      False

[200 rows x 4 columns]

In [24]:
import pandas as pd

df1 = pd.read_csv("./csv/data.csv")
df2 = pd.read_csv("./csv/data2.csv")

df1

id FirstName            Skills
0  1001     Frodo     web developer
1  1002   Samwise    Data Scientist
2  1003   Gandalf  Machine Engineer
3  1004    Pippin       AI Engineer

In [25]:
df2

id FirstName   Age
0  1001     Frodo    50
1  1002   Samwise    39
2  1006   Legolas  2931
3  1007    Elrond  6520
4  1008  Barromir    51

In [28]:
import pandas as pd

df1 = pd.read_csv("./csv/data.csv")
df2 = pd.read_csv("./csv/data2.csv")

dfmerge = pd.concat([df1,df2])
dfmerge

id FirstName            Skills     Age
0  1001     Frodo     web developer     NaN
1  1002   Samwise    Data Scientist     NaN
2  1003   Gandalf  Machine Engineer     NaN
3  1004    Pippin       AI Engineer     NaN
0  1001     Frodo               NaN    50.0
1  1002   Samwise               NaN    39.0
2  1006   Legolas               NaN  2931.0
3  1007    Elrond               NaN  6520.0
4  1008  Barromir               NaN    51.0

In [2]:
import pandas as pd

# df1 = pd.read_csv("./csv/data.csv")
df2 = pd.read_csv("./csv/data2.csv")

df2

# dfmerge = pd.concat([df1,df2])
# dfmerge

id FirstName   Age
0  1001     Frodo    50
1  1002   Samwise    39
2  1006   Legolas  2931
3  1007    Elrond  6520
4  1008  Barromir    51

In [5]:
import pandas as pd

df3 = pd.read_csv("./csv/data2.csv")

df3

id FirstName   Age    menue
0  1001     Frodo    50   burger
1  1002   Samwise    39   quarma
2  1006   Legolas  2931   qoufta
3  1007    Elrond  6520   mutton
4  1008  Barromir    51   zinger

In [7]:
import pandas as pd

df1 = pd.read_csv("./csv/data.csv")
df2 = pd.read_csv("./csv/data2.csv")

dfmerge = pd.concat([df1,df2])
dfmerge

id FirstName            Skills     Age    menue
0  1001     Frodo     web developer     NaN      NaN
1  1002   Samwise    Data Scientist     NaN      NaN
2  1003   Gandalf  Machine Engineer     NaN      NaN
3  1004    Pippin       AI Engineer     NaN      NaN
0  1001     Frodo               NaN    50.0   burger
1  1002   Samwise               NaN    39.0   quarma
2  1006   Legolas               NaN  2931.0   qoufta
3  1007    Elrond               NaN  6520.0   mutton
4  1008  Barromir               NaN    51.0   zinger

In [15]:
import pandas as pd

df1 = pd.read_csv("./csv/data.csv")
df2 = pd.read_csv("./csv/data2.csv")

dfmerge = pd.merge(df2,df1, how = "right")
dfmerge

id FirstName   Age    menue            Skills
0  1001     Frodo  50.0   burger     web developer
1  1002   Samwise  39.0   quarma    Data Scientist
2  1003   Gandalf   NaN      NaN  Machine Engineer
3  1004    Pippin   NaN      NaN       AI Engineer

In [25]:
# import sys
# import pandas as pd
# # import matplotlib 

# # matplotlib.use("Agg")
# import matplotlib.pyplot as plt

# df = pd.read_csv("./csv/data.csv")
# df.plot()

# plt.savefig("output.png")




In [2]:
#Three lines to make our compiler able to draw:
import sys
import matplotlib
matplotlib.use('Agg')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('./csv/data3.csv')
df.plot()
plt.show()

#Two  lines to make our compiler able to draw:
plt.savefig("output.jpg")
sys.stdout.flush()

ModuleNotFoundError: No module named 'matplotlib'

In [9]:
#Three lines to make our compiler able to draw:
# import sys
# import matplotlib
# matplotlib.use('Agg')

# import pandas as pd
# import matplotlib.pyplot as plt

# df = pd.read_csv('./csv/data3.csv')
# df.plot()
# plt.show()

# plt.savefig("ouput.png")
# sys.stdout.flush()

C:\Users\Professor\AppData\Local\Temp\ipykernel_780\62849724.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
